// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SaleManager.Core.Entities
{
    public partial class Companies
    {
        public Companies()
        {
            CompanyUsers = new HashSet<CompanyUsers>();
            Customers = new HashSet<Customers>();
            Employees = new HashSet<Employees>();
            Orders = new HashSet<Orders>();
        }

        [Key]
        public int CompanyID { get; set; }
        [Required]
        [StringLength(50)]
        public string CompanyName { get; set; }
        [StringLength(50)]
        public string Adress { get; set; }
        [StringLength(20)]
        public string Country { get; set; }
        [StringLength(10)]
        public string Currency { get; set; }

        [InverseProperty("Company")]
        public virtual ICollection<CompanyUsers> CompanyUsers { get; set; }
        [InverseProperty("Company")]
        public virtual ICollection<Customers> Customers { get; set; }
        [InverseProperty("Company")]
        public virtual ICollection<Employees> Employees { get; set; }
        [InverseProperty("Company")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}