// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SaleManager.Core.Entities
{
    public partial class CompanyUsers
    {
        [Key]
        public int ID { get; set; }
        public int? CompanyID { get; set; }
        [StringLength(50)]
        public string UserName { get; set; }

        [ForeignKey(nameof(CompanyID))]
        [InverseProperty(nameof(Companies.CompanyUsers))]
        public virtual Companies Company { get; set; }
    }
}