// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SaleManager.Core.Entities
{
    [Index(nameof(CustomerID), Name = "IX_Orders_CustomerID")]
    [Index(nameof(EmployeeID), Name = "IX_Orders_EmployeeID")]
    [Index(nameof(ShipVia), Name = "IX_Orders_ShipVia")]
    public partial class Orders
    {
        public Orders()
        {
            Order_Details = new HashSet<Order_Details>();
        }

        [Key]
        public int OrderID { get; set; }
        public int CustomerID { get; set; }
        public int? EmployeeID { get; set; }
        [StringLength(150)]
        public string OrderName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? OrderDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RequiredDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ShippedDate { get; set; }
        public int? ShipVia { get; set; }
        [Column(TypeName = "money")]
        public decimal? Total { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? TaxRate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? TaxTotal { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? DiscountRate { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? DiscountTotal { get; set; }
        public string ShipFees { get; set; }
        public string AssemblyFees { get; set; }
        public string PaymentType { get; set; }
        [StringLength(60)]
        public string ShipAddress { get; set; }
        [StringLength(15)]
        public string ShipCity { get; set; }
        [StringLength(15)]
        public string ShipRegion { get; set; }
        [StringLength(10)]
        public string ShipPostalCode { get; set; }
        [StringLength(15)]
        public string ShipCountry { get; set; }
        public bool? Approved { get; set; }
        [Column(TypeName = "money")]
        public decimal? GrandTotal { get; set; }
        [StringLength(10)]
        public string Currency { get; set; }
        [StringLength(50)]
        public string OrderStatus { get; set; }
        public int? CompanyID { get; set; }
        [StringLength(50)]
        public string OrderNumber { get; set; }

        [ForeignKey(nameof(CompanyID))]
        [InverseProperty(nameof(Companies.Orders))]
        public virtual Companies Company { get; set; }
        [ForeignKey(nameof(CustomerID))]
        [InverseProperty(nameof(Customers.Orders))]
        public virtual Customers Customer { get; set; }
        [ForeignKey(nameof(EmployeeID))]
        [InverseProperty(nameof(Employees.Orders))]
        public virtual Employees Employee { get; set; }
        [ForeignKey(nameof(ShipVia))]
        [InverseProperty(nameof(Shippers.Orders))]
        public virtual Shippers ShipViaNavigation { get; set; }
        [InverseProperty("Order")]
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}