// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SaleManager.Core.Entities
{
    [Index(nameof(City), Name = "City")]
    [Index(nameof(CompanyName), Name = "CompanyName")]
    [Index(nameof(PostalCode), Name = "PostalCode")]
    [Index(nameof(Region), Name = "Region")]
    public partial class Customers
    {
        public Customers()
        {
            Orders = new HashSet<Orders>();
        }

        [Key]
        public int CustomerID { get; set; }
        [Required]
        [StringLength(150)]
        public string CompanyName { get; set; }
        [StringLength(100)]
        public string ContactName { get; set; }
        [StringLength(50)]
        public string ContactTitle { get; set; }
        public string TaxOffice { get; set; }
        public string TaxId { get; set; }
        [StringLength(200)]
        public string Address { get; set; }
        [StringLength(15)]
        public string City { get; set; }
        [StringLength(15)]
        public string Region { get; set; }
        [StringLength(10)]
        public string PostalCode { get; set; }
        [StringLength(15)]
        public string Country { get; set; }
        [StringLength(24)]
        public string Phone { get; set; }
        public string EMail { get; set; }
        public bool? Active { get; set; }
        public string Details { get; set; }
        public int? CompanyID { get; set; }

        [ForeignKey(nameof(CompanyID))]
        [InverseProperty(nameof(Companies.Customers))]
        public virtual Companies Company { get; set; }
        [InverseProperty("Customer")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}