// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SaleManager.Core.Entities
{
    [Table("Order Details")]
    [Index(nameof(OrderID), Name = "IX_Order Details_OrderID")]
    [Index(nameof(ProductID), Name = "IX_Order Details_ProductID")]
    public partial class Order_Details
    {
        [Key]
        public int Id { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        [Column(TypeName = "money")]
        public decimal UnitPrice { get; set; }
        public short Quantity { get; set; }
        public float? Discount { get; set; }
        public float? DiscountPercent { get; set; }
        [Column(TypeName = "money")]
        public decimal? Total { get; set; }
        public string Details { get; set; }

        [ForeignKey(nameof(OrderID))]
        [InverseProperty(nameof(Orders.Order_Details))]
        public virtual Orders Order { get; set; }
        [ForeignKey(nameof(ProductID))]
        [InverseProperty(nameof(Products.Order_Details))]
        public virtual Products Product { get; set; }
    }
}