// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SaleManager.Core.Entities
{
    [Index(nameof(ProductID), Name = "IX_ProductParts_ProductID")]
    [Index(nameof(SpareID), Name = "IX_ProductParts_SpareID")]
    public partial class ProductParts
    {
        [Key]
        public int ID { get; set; }
        public int? SpareID { get; set; }
        public int? ProductID { get; set; }
        public int? Quantity { get; set; }
        public bool? Prepared { get; set; }
        public bool? Sent { get; set; }
        [StringLength(50)]
        public string Details { get; set; }
        [Column(TypeName = "money")]
        public decimal? CashCost { get; set; }
        [Column(TypeName = "money")]
        public decimal? ChecqueCost { get; set; }

        [ForeignKey(nameof(ProductID))]
        [InverseProperty(nameof(Products.ProductParts))]
        public virtual Products Product { get; set; }
        [ForeignKey(nameof(SpareID))]
        [InverseProperty(nameof(SpareParts.ProductParts))]
        public virtual SpareParts Spare { get; set; }
    }
}