// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace SaleManager.Core.Entities
{
    public partial class SpareParts
    {
        public SpareParts()
        {
            ProductParts = new HashSet<ProductParts>();
        }

        [Key]
        public int SpareID { get; set; }
        [Required]
        [StringLength(50)]
        public string SpareName { get; set; }
        [StringLength(50)]
        public string Units { get; set; }
        [Column(TypeName = "money")]
        public decimal? CashCost { get; set; }
        [Column(TypeName = "money")]
        public decimal? ChecqueCost { get; set; }
        [StringLength(50)]
        public string Type { get; set; }
        [StringLength(50)]
        public string Details { get; set; }
        public int? CompanyID { get; set; }

        [InverseProperty("Spare")]
        public virtual ICollection<ProductParts> ProductParts { get; set; }
    }
}